### ISSUE TITLE
testing: computer setup following aiida-vasp fails

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-plugin-template#6]
In order to make the setup of computers (+calculations,...) in the tests more clean, I'm trying to follow the procedure in aiida-vasp

https://github.com/DropD/aiida-vasp/blob/a2e1f7e395e1b39c1158536260f5dc58a4d0aec0/aiida_vasp/utils/fixtures/data.py#L17-L37

Unfortunately, this does not work for me (with `unittest`).
This is the code I am testing:
https://github.com/aiidateam/aiida-plugin-template/blob/770e8a17da857251330ea046905504a61588f4ac/aiida_plugin_template/tests/test_calculations.py#L9-L35

And this is the result
```
$ TEST_BACKEND=django python -m unittest discover
E
======================================================================
ERROR: test_empty (test_calculations.TestMultiply)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_calculations.py", line 31, in setUp
    computer = self.get_localhost()
  File "test_calculations.py", line 25, in get_localhost
    enabled_state=True)
  File "/Users/leopold/Applications/aiida_core/aiida/orm/implementation/django/computer.py", line 66, in __init__
    self.set(**kwargs)
  File "/Users/leopold/Applications/aiida_core/aiida/orm/implementation/django/computer.py", line 78, in set
    method(v)
  File "/Users/leopold/Applications/aiida_core/aiida/orm/implementation/django/computer.py", line 227, in set_workdir
    self._set_metadata(metadata)
  File "/Users/leopold/Applications/aiida_core/aiida/orm/implementation/django/computer.py", line 195, in _set_metadata
    self.dbcomputer.metadata = json.dumps(metadata_dict)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_master/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_master/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_master/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_master/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <test_calculations.TestMultiply testMethod=test_empty> is not JSON serializable

----------------------------------------------------------------------
Ran 1 test in 7.138s

FAILED (errors=1)
```

For some reason it tries to serialize the test_empty method of the test class... I've no idea why.

**Comment by ltalirz** [comment]
this was a stupid bug, it should have been
`def get_localhost(self, localhost_dir='/tmp'):`

Perhaps I'll make a pull request for a check of the `temp_dir` in `Code`.
